#-*- mode:org; mode:visual-line; coding:utf-8; -*-
codepad.el --- Emacs integration for [[http://codepad.org][codepad.org]].

See [[http://codepad.org]].

Codepad is a pastebin where you can paste code and share it on a chat or via email. Codepad also provides an online compiler/interpreter and can run your programs online.

emacs-codepad provides an Emacs integration for Codepad. Currently you can use it to paste your code to and fetch code from Codepad.

Contributors are welcome!

codepad.el is based on [[http://github.com/defunkt/gist.el/blob/master/gist.el][gist.el]] which was written by Christian Neukirchen and others. codepad.el is written by Rüdiger Sonderfeld. You can contact me via E-Mail: [[mailto:ruediger@c-plusplus.de][ruediger@c-plusplus.de]].

Thanks to Thomas Weidner <[[mailto:thomas001le@gmail.com][thomas001le@gmail.com]]> for his patches and help. Thanks to Lorenzo Villani <[[mailto:lvillani@binaryhelix.net][lvillani@binaryhelix.net]]> for fixing the "error in process filter: Symbol's value as variable is void: url-max-redirections" issue.

* Installation
Codepad was developed for Emacs 23.1+. codepad.el has problems with older versions of Emacs (url.el)! If codepad.el won't work please upgrade your Emacs.

Installation is straight forward:

Add the following lines to your =~/.emacs=:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "PATH") ;; replace PATH with the path to codepad.el
  (autoload 'codepad-paste-region "codepad" "Paste region to codepad.org." t)
  (autoload 'codepad-paste-buffer "codepad" "Paste buffer to codepad.org." t)
  (autoload 'codepad-fetch-code "codepad" "Fetch code from codepad.org." t)
#+END_SRC

Restart Emacs (or evaluate those lines) and you can use codepad.el by calling =M-x codepad-paste-region= to paste the current selected region or =M-x codepad-paste-buffer= to paste the current selected buffer.

You can configure codepad.el by calling =M-x customize-group codepad=.

Codepad.el is also available via [[https://github.com/dimitri/el-get][el-get]] and it is currently part of [[http://overlays.gentoo.org/proj/emacs/browser/emacs-overlay/app-emacs/codepad][Gentoo's Emacs Overlays]].
